### ISSUE TITLE
Option to get one object instead of list

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#329]
Common task — get exactly one object from the db.

```java
// Can be null.
final User user = storIOSQLite 
  .get()
  .object(User.class)
  .withQuery(new Query.Builder()
    .table("users")
    .where("user_id = ?")
    .whereArgs(userId)
    .build())
  .prepare()
  .executeAsBlocking()
```

I think, it should return `null` if `cursor.getCount() == 0` for `executeAsBlocking()`, for RxJava it should just complete normally without emitting null, so it'll be possible to apply `defaultOrEmpty` Operator.

```java
storIOSQLite 
  .get()
  .object(User.class)
  .withQuery(new Query.Builder()
    .table("users")
    .where("user_id = ?")
    .whereArgs(userId)
    .build())
  .prepare()
  .createObservable()
  .defaultIfEmpty(loadUserFromNetwork(userId)) // elegant?
```

@nikitin-da what do you think?

**Comment by nikitin-da** [comment]
Yes, I agree that 'null' for blocking variant will be obvious. For rx, we can simply replace 'loadUserFromNetwork' with swithing ui state to empty in main thread, don,t we?

**Comment by artem-zinnatullin** [comment]
I am moving this to 1.1.0

**Comment by artem-zinnatullin** [comment]
cc @benjchristensen

**Comment by Rainer-Lang** [comment]
Would be nice to have this. I really need it.

**Comment by geralt-encore** [comment]
@artem-zinnatullin Hey! I have done this feature for the executeAsBlocking case, but not for createObservable yet, because of a lack of experience with RxJava on that level. So should I make a PR? And if yes what base branch should I choose?
It is my first serious contribution to open source and I am very excited about it =), so sorry for my newbie questions.

**Comment by geralt-encore** [comment]
Hi, Artem!
I have started to implement Rx part and faced with some difficulties because a lack of experience with it, so I need your advice. I tried to deal with it in that way:

    storIOSQLite.observeChangesInTables(tables)
                    .map(MapSomethingToExecuteAsBlocking.newInstance(this))
                    .startWith(Observable.create(OnSubscribeExecuteAsBlocking.newInstance(this)))
                    .filter(new Func1<T, Boolean>() {
                        @Override
                        public Boolean call(T t) {
                            return t != null;
                        }
                    })
                    .first()
                    .subscribeOn(Schedulers.io());

The problem is that in the case when there are no objects satisfying query - observable never completes and it is impossible to use defaultIfEmpty for example.
I am probably missing something really simple, but I haven't discovered it yet.
I'll very appreciate your advice.

**Comment by artem-zinnatullin** [comment]
@geralt-encore cool!

So, you should not `filter()` the emission in this case because you're just skipping `nulls` now and it's incorrect behavior. Also, `first()` will emit only one result and then `Observable` will be completed.

Looks like you understand Russian :smile:, so you can try to watch my talk about Rx and it'll hopefully help you understand Rx better https://events.yandex.ru/lib/talks/3106/

I'd rewrite this to something like:

```java
observeChangesInTables(tables)
  .map(MapSomethingToExecuteAsBlocking.newInstance(this)) // On each change get new result
  .startWith(Observable.create(OnSubscribeExecuteAsBlocking.newInstance(this))) // Start with initial result
  .subscribeOn(Schedulers.io());
```

Should work fine!

**Comment by geralt-encore** [comment]
@artem-zinnatullin I am not sure that I explained my question well. I was talking about the implementation of `executeAsBlocking` in `PreparedGetObject`. I am using `first` because I need take only one object. And I need to use `filter` because `executeAsBlocking` can return `null` in the case when there is no object that satisfies query was found. Is it approach completely wrong?

**Comment by artem-zinnatullin** [comment]
`first` (same as `take(1)`) will take one result of emission but then we won't receive updates on table changes.

`null` is valid result for `executeAsBlocking()`, so it should be the same for `rx` approach :)

**Comment by geralt-encore** [comment]
Oh, now I understand the problem with `first`. So are you sure about emitting `null` and leaving to end users to handle that case?

**Comment by artem-zinnatullin** [comment]
But we already do this for `executeAsBlocking`, Rx support should provide same results.

**Comment by geralt-encore** [comment]
@artem-zinnatullin Looks like this issue can be closed =)

**Comment by artem-zinnatullin** [comment]
@geralt-encore yay! Thanks a lot!

**Comment by artem-zinnatullin** [comment]
It was pleasure to merge your PRs! Hope @nikitin-da thinks so too :smile:

**Comment by geralt-encore** [comment]
Thanks! I've learned a lot from you guys and looking forward to continuing to contribute into StorIO

**Comment by nikitin-da** [comment]
Definitely! Thank you, Ilya!
