### ISSUE TITLE
Examples subqueries

### ISSUE THREAD

**Issue by oneassasin** [pushtorefresh/storio#431]
Please, write.

**Comment by artem-zinnatullin** [comment]
Can you please give more description to the issue?

You want us to add examples with `RawQuery` which will use subqueries or what? If so -> there is no difference between standard raw query for `SQLiteDatabase` :)

**Comment by oneassasin** [comment]
I mean the construction of queries with subqueries using Query.
```java 
DBUtils.getRxContentResolver(getActivity())
        .get()
        .cursor()
        .withQuery(RawQuery.builder()
            .query("SELECT * FROM ? JOIN ? ON ?.? = ?.? WHERE (? = 1400 AND ? = ?)")
            .args(WReaderDBStore.HourlyTemperature.TABLE_NAME,
                WReaderDBStore.WeatherTable.TABLE_NAME,
                WReaderDBStore.HourlyTemperature.TABLE_NAME,
                WReaderDBStore.HourlyTemperature.weatherId,
                WReaderDBStore.WeatherTable.TABLE_NAME,
                WReaderDBStore.WeatherTable.cityId,
                WReaderDBStore.HourlyTemperature.time,
                WReaderDBStore.WeatherTable.cityId,
                String.valueOf(cityID))
            .build())
        .prepare()
        .createObservable();
```
RawQuery not suitable as an argument for a method withQuery.
I`m using 
```groovy
compile 'com.pushtorefresh.storio:content-resolver:1.0.0'
compile 'com.pushtorefresh.storio:sqlite:1.0.0'
```

**Comment by artem-zinnatullin** [comment]
You can not use `RawQuery` with `StorIOContentResolver`, it's limitation of `ContentResolver` and `ContentProvider` in general, because you can use something different from `SQLiteDatabase` under the `ContentProvider`.

You should use `StorIOSQLite` instead of `StorIOContentResolver` if you don't have `ContentProvider` and you just want to work with `SQLiteDatabase`.

Or if you need to use `SQLiteDatabase` under the `ContentProvider`, you need to create some `Uri` that will use `SQL` under the hood of the `ContentProvider` `.get()` with this `Uri`.
