### ISSUE TITLE
PutResult with 0 updated rows

### ISSUE THREAD

**Issue by krpiotrek** [pushtorefresh/storio#453]
Hey,
Is this a bug or it's intended and I'm missing something - I cannot create PutResult with zero rows updated - both newUpdateResult(...) methods take numberOfRowsUpdated as a primitive int, while constructor's
```
   if (numberOfRowsUpdated != null && numberOfRowsUpdated < 1) {
        throw new IllegalArgumentException("Number of rows updated must be > 0");
   }
```
 assumes that you either pass null value (impossible via newUpdateResult method) or > 0 value

**Comment by artem-zinnatullin** [comment]
Put is Insert or Update, so correct variant of `PutResult`: one inserted row or one or several updated rows (> 0).

You want to create `PutResult` that represent update with 0 updated rows?

**Comment by krpiotrek** [comment]
Yep, exactly, it's pretty normal for update query to end up with no rows updated, is such PutResult doable with current API?

**Comment by artem-zinnatullin** [comment]
But in terms of Put Operation it is incorrect result -> if no rows were updated, you need to insert it don't you?

BTW this is how DefaultPutResolver works.

**Comment by krpiotrek** [comment]
Is it a contract of DefaultPutResolver or PutResolver in general?
I have implemented my own PutResolver which does something like this :
if item doesnt exist - insert
if item exists - check is data synced (user can modify data offline) -> if synced, update / if not synced, leave it as it is

**Comment by artem-zinnatullin** [comment]
I understand your case now.

It's contract of `PutResolver` and `PutResult` in general, we've followed same semantic as `SQLiteDatabase` here, it will return that one row was updated even if all columns were same.

In general, we can not guarantee this for `DefaultPutResolver` because we check only existence of row for `Query.where(updateQuery.where()).whereArgs(updateQuery.whereArgs())`, `SQLiteDatabase` won't return `0` even if all columns were same and you will get different behavior with your resolver…

But probably, it's okay result of Put Operation for your and other similar cases when we need to understand that we have exactly same row in the db after Put Operation: `wasInserted() == false && wasUpdated() == true && numberOfRowsUpdated()  == 0`.

I think we can allow it and write about general contract of default implementations in the javadoc.

@nikitin-da your opinion?

**Comment by krpiotrek** [comment]
Just to be clear - SQLiteDatabase will return 0 for an update statement with where clause like "WHERE id = some_id AND some_flag = true" if the some_flag is set to false. I'm not sure if returning wasUpdated = true for this case intuitive

**Comment by artem-zinnatullin** [comment]
> Just to be clear - SQLiteDatabase will return 0 for an update statement with where clause like "WHERE id = some_id AND some_flag = true" if the some_flag is set to false. I'm not sure if returning wasUpdated = true for this case is intuitive

Sure, but this is not the case, and it's normal behavior, `DefaultPutResolver` will make `query` with this `where` and `whereArgs` and  if result will be `0` it will make insert, otherwise — update and update will return `> 1` -> `wasUpdated` will be `true`.

**Comment by nikitin-da** [comment]
I think we should allow `PutResult` with `0` updated rows. 
Like I said before (https://github.com/pushtorefresh/storio/pull/423) it's just `DefaultPutResolver` feature that `0` inserted and `0` updated - impossible. 
Another resolvers may, for example, check object for equality or some other condition before `update` call. So this `PutResult` will be required.
@krpiotrek, if I understand you correctly, `some_flag` it is not part of compound primary key.
And you want not to `put`, just `update` multiple rows by some rule. 
If so, `0` updated rows also will be required. But you will need this only when you didn't carried out this operation with objects in memory, will not you?

**Comment by artem-zinnatullin** [comment]
Okay, so, let's make it in 1.0.1, I'll try to prepare PR and release today, looks like it's critical for @krpiotrek  :)

@nikitin-da can you be online for a few hours please?

**Comment by nikitin-da** [comment]
ok

**Comment by artem-zinnatullin** [comment]
@krpiotrek please try v1.0.1!

**Comment by krpiotrek** [comment]
thanks ! :+1:
