### ISSUE TITLE
Why doesn't limit() method of query builder accept integer args?

### ISSUE THREAD

**Issue by vokilam** [pushtorefresh/storio#515]
Although I understand that `LIMIT` clause [may be pretty complex](https://www.sqlite.org/lang_select.html), I think that it would be handy to have overloaded versions `limit(int)` and `limit(int, int)` for vast majority of cases. Are there any implications of doing so?

**Comment by artem-zinnatullin** [comment]
The main reason why we don't have `limit(n)` is that we don't want to generate any kind of SQL as part of the StorIO, because SQL is not very easy language to parse & validate.

But, I'd agree that `limit(n)` and `limit(n, m)` looks like easy, useful and valid feature!

I think we can add it in the next release, feel free to send PRs or wait until we implement it (we'll comment here if we start our work).

@nikitin-da please comment

**Comment by nikitin-da** [comment]
I agree, it should be nice feature, I'll implement it.

**Comment by artem-zinnatullin** [comment]
Cool :) Added to v1.4.0 milestone!

**Comment by artem-zinnatullin** [comment]
@vokilam StorIO 1.4.0 was just released and should be available in 10-20 minutes, hope you'll like it!

**Comment by vokilam** [comment]
Awesome!
