### ISSUE TITLE
Backpressure problem with table observers

### ISSUE THREAD

**Issue by faifai21** [pushtorefresh/storio#559]
Hey guys,

I'm using RxJava to observe table changes. I've seen this exception when I'm making lots of inserts/updates in really quick succession. 

```
java.lang.IllegalStateException: more items arrived than were requested
at rx.internal.producers.ProducerArbiter.produced(ProducerArbiter.java:98)
at rx.internal.operators.OperatorConcat$ConcatInnerSubscriber.onNext(OperatorConcat.java:208)
at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
at rx.internal.operators.OperatorFilter$1.onNext(OperatorFilter.java:54)
at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:224)
at rx.subjects.PublishSubject.onNext(PublishSubject.java:114)
at rx.observers.SerializedObserver.onNext(SerializedObserver.java:159)
at rx.subjects.SerializedSubject.onNext(SerializedSubject.java:65)
at com.pushtorefresh.storio.internal.RxChangesBus.onNext(RxChangesBus.java:18)
at com.pushtorefresh.storio.internal.ChangesBus.onNext(ChangesBus.java:26)
at com.pushtorefresh.storio.sqlite.impl.DefaultStorIOSQLite$InternalImpl.notifyAboutChanges(DefaultStorIOSQLite.java:414)
at com.pushtorefresh.storio.sqlite.operations.put.PreparedPutCollectionOfObjects.executeAsBlocking(PreparedPutCollectionOfObjects.java:140)
at com.everalbum.everstore.sql.SQLEngine.submit(SQLEngine.java:204)
at com.everalbum.everstore.EverStoreManager.saveItems(EverStoreManager.java:113)
at com.everalbum.everalbumapp.AssetUploadFinishQueue.flush(AssetUploadFinishQueue.java:91)
```

Initially I was inserting a large amount of items (4k~) or so individually in rapid succession. This error was a lot more common back then. I then started batching inserts in batches of 25, and this error became a lot less common. I still see it every now and then. I reckon that I could completely prevent it from happening if I set the batch size to 50, but it would mean that I delay updating the ui. It isn't ideal but it works.

I guess I've got two questions: Do the observables returned from querying a table handle backpressure properly? Is there a way to get the latest changes on the table instead of getting the entire table whenever a change happens?

Cheers,
Fai

**Comment by artem-zinnatullin** [comment]
Hello, @faifai21!

The problem here is if we start handling backpressure on our side we have only two choices (in general):

1. Drop events — may lead to inconsistency of the client app since it may not receive some notification.
2. Buffer and group notifications — we can do it, and it looks better than dropping events, but, but it may lead to delays in the StorIO notifications system and if you'll do things like inserting 4k objects it'll lead to consumption of large amounts of memory inside the library.

Common recommendation: use `put().objects()` since it wraps changes into a transaction and then emits one pack of changes (according to stacktrace you already use it :+1:).

Is this critical for you (I hope you don't do releases on Fridays :smile: )? 

If yes — I can work on this asap, and we'll ship 1.6.2 in a couple days, or if it's not very critical, I'd work on it — we'll ship it in 1.7.0 next week.

**Comment by faifai21** [comment]
Hi @artem-zinnatullin!

Thanks for the quick response! It isn't critical. No releases this Friday haha! I think i'll just increase the batch size to 40 or so (I'll play around with the value and see what works best) and that will probably solve the problem. The other thing that I noticed is that once I get this exception, I actually stop getting anymore notifications to changes to the table. Is there a way to perhaps consume this exception and reset RxChangeBus?

**Comment by artem-zinnatullin** [comment]
>The other thing that I noticed is that once I get this exception, I actually stop getting anymore notifications to changes to the table.

Whoa, by default unhandled exception should crash the app, strange that it works after this.

>Is there a way to perhaps consume this exception and reset RxChangeBus?

As said — it should crash the app, but looks like you're setting `onError` handler so `RxChangesBus` just freezes in `onError` state. Currently we don't expose api to reset `RxChangesBus` and if we add backpressure support — we won't need it.

At the moment you can provide your own implementation of notifications system because StorIO is just an abstraction with some default implementation (yeah, we like flexibility).

If so — I hope I'll add backpressure tolerance to the StorIO this weekend and we'll ship 1.7.0 next week!

**Comment by faifai21** [comment]
Yep, I've got `onError` catching that exception somewhere along our pipeline, so that's preventing the app from crashing. And yea, you're right, with backpressure, we shouldn't need to reset the changes bus.

Out of curiosity, where would I add my own implementation of the notifications system?

**Comment by artem-zinnatullin** [comment]
>Out of curiosity, where would I add my own implementation of the notifications system?

You can create own version of `StorIOSQLite` and implement it as you wish (probably even reuse some parts of `DefaultStorIOSQLite`).

But, I recommend just wait for 1.7.0 :smile:

**Comment by faifai21** [comment]
Yep, will do! I have too many things in my queue right now to worry about implementing a completely new notification system haha!

**Comment by akarnokd** [comment]
Disclaimer: I'm not familiar with StorIO and its API.

What I'd do, on the API level is to ask the user for an Observable instead of values:

```
Observable<?> save(Observable<T> objects);
```

and return a completion observable for it. This shifts the backpressure responsibility to the caller who now can apply `onBackpressureXXX` knowingly or simply provide something that naturally supports backpressure like `from(Iterable)`.

`BackpressureBufferLastOperator` [Issue](https://github.com/square/sqlbrite/issues/73) looks similar to `onBackpressureLatest` [2.x](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/OperatorOnBackpressureLatest.java) with the exception that it keeps reemitting the last value if I'd request 1 by 1 and upstream doesn't send anything.

**Comment by artem-zinnatullin** [comment]
> This shifts the backpressure responsibility to the caller who now can apply onBackpressureXXX knowingly or simply provide something that naturally supports backpressure like from(Iterable).

If we do so users will have to deal with backpressure each time they want to write/read something to/from the db, which will make code more complicated than it should be.

I hope I'll be able to implement backpressure with buffering without `OutOfMemoryError`, because we send only `table` name and usually db does not have many tables so if buffering will be done correctly will just merge `table` names into a `Set` and then emit this `Set` without loosing information about changes!
