### ISSUE TITLE
How to store a single entity in the two tables?

### ISSUE THREAD

**Issue by wpbloger** [pushtorefresh/storio#578]
Hello.
I have tried different libraries to work with a sqlite, but there is not the flexibility that I need.
Specifically I need to store a single entity in the two tables for a particular data cache.
How can you do it correctly by a storio?
------------------------------------------------------------------------------------------------------------------
Здравствуйте.
Я уже пробовал разные библиотеки для работы с sqlite, но нигде мне не хватает гибкости для реализации моих идей.
А именно мне нужно хранить одну сущность в двух таблицах, для особого кэширования данных.
Как можно это правильно сделать с помощью это библиотеки?
Читал обзор на хабре, вы писали что это без труда можно сделать.
Структура таблиц будет полностью идентична, просто нужны две таблицы...
Пс. с наступающим вас нг!

**Comment by nikitin-da** [comment]
Hi, @wpbloger !
If you really need it, you can construct custom [`put`](https://github.com/pushtorefresh/storio/blob/master/storio-sqlite/src/main/java/com/pushtorefresh/storio/sqlite/operations/put/PreparedPut.java), [`get`](https://github.com/pushtorefresh/storio/blob/master/storio-sqlite/src/main/java/com/pushtorefresh/storio/sqlite/operations/get/GetResolver.java) and [`delete`](https://github.com/pushtorefresh/storio/blob/master/storio-sqlite/src/main/java/com/pushtorefresh/storio/sqlite/operations/delete/DeleteResolver.java) resolvers and use it instead of default implementations.
As example for `put`, just override `performPut` method:
```java
public PutResult performPut(StorIOSQLite storIOSQLite, User user) {
    // create insert or update queries 
    storIOSQLite.internal().insert(insertQueryFirstTable, contentValues);
    storIOSQLite.internal().insert(insertQuerySecondTable, contentValues);
    // construct put result
}
```

Feel free to ask questions, BTW we would like to keep GitHub issues for feature requests and bug reports if it's possible, you can ask questions about usage patterns on StackOverflow with `storio` tag.

Happy new year! :christmas_tree:

**Comment by artem-zinnatullin** [comment]
@nikitin-da gave right solution, the only recommendation from me — wrap each operation into transaction for data consistency, i.e.:

```java
public PutResult performPut(StorIOSQLite storIOSQLite, User user) {
    // create insert or update queries 
    storIOSQLite.internal().beginTransaction();

    try {
        storIOSQLite.internal().insert(insertQueryFirstTable, contentValues);
        storIOSQLite.internal().insert(insertQuerySecondTable, contentValues);
        storIOSQLite.internal().setTransactionSuccessful();
    } finally {
        storIOSQLite.internal().endTransaction();
    }
}
```
