### ISSUE TITLE
How exactly does the .where() work with .whereArgs()

### ISSUE THREAD

**Issue by sreejithraman** [pushtorefresh/storio#619]
If I wanted to have AND I know I can do something like this:

````JAVA
.where(Table.COLUMN_ID + " = ? AND " + Table.COLUMN_TYPE + " = ?")
.whereArgs(id, type)
````

But what if I wanted to match it with a list of ids or a list of types? Can I do something like this:

````JAVA
.where(Table.COLUMN_ID + " = ? AND " + Table.COLUMN_TYPE + " = ?")
.whereArgs(
idList, // where this is a List<Id>
typeList // where this is a List<Type>
)
````

**Comment by artem-zinnatullin** [comment]
Hi @sreejithraman!

So, basically it calls `.toString()` on each argument passed to `whereArgs()` and `whereArgs()` accepts an array, so if you won't convert your list to array, it'll see it as one object and use its `toString()` value.

If you need to specify a list, we have useful method `Queries.placeholders()` to create required amount of `?` placeholders and just call `.toArray()` on your list since `whereArgs()` accepts an array.

Here is the example:

```java
Query.builder()
  .table(Table.NAME)
  .where(Table.COLUMN_ID + " = ?  " + 
        "AND " + 
        Table.COLUMN_TYPE + " IN (" + Queries.placeholders(types.size()) + ")")
  .whereArgs(types.toArray())
  .build()
```

**Comment by sreejithraman** [comment]
@artem-zinnatullin for the above query that you wrote, is that a mistake because you never specified the the id. Or am i missing something?

**Comment by artem-zinnatullin** [comment]
@sreejithraman right, fixed, thanks!
