### ISSUE TITLE
Using Robolectric for testing

### ISSUE THREAD

**Issue by maxim-pandra** [pushtorefresh/storio#677]
Hi @artem-zinnatullin 
I have listened your podcast and, if my memory serves me correctly, you said, that we should only use robolectric to mock and test only simple framework related objects (Bundles, ContentValues etc). Everything else we should test on device/emulator. 

If that is correct then why in sample app in RelationsTest you use robolectric to test whole database behavior and using RuntimeEnviroment.application?

Sorry if my question is stupid or absurd. I am not really expirenced with Robolectric and tests in general.
And thank you guys for your amazing work for the comunity! Keep it up!

**Comment by artem-zinnatullin** [comment]
Hey hey! Your question is absolutely NOT stupid.

Let me describe why and for what we use Robolectric in StorIO tests.

What it gives us:

1. Robolectric provides SQLite support including db itself that runs in RAM and Android SDK classes like `SQLiteOpenHelper`, that allows us test `StorIOSQLite`.
2. Robolectric provides `ContentProvider` impl so we can also test `StorIOContentResolver`.

Why we use it:

I would prefer to run our tests on real Android (emulators), but the problem here is that our CI which is currently [Travis CI](https://travis-ci.org) is already very flacky and can fail even simple build without good reasons (usually it's insufficient amount of memory or just build freeze) and when you add Android Emulator to such build, chances it'll fail will highly increase.

On own CI I would run our tests on Android Emulators.

>If that is correct then why in sample app in RelationsTest you use robolectric to test whole database behavior and using RuntimeEnviroment.application?

Yes.

>Everything else we should test on device/emulator.

Yes.

Hope that helps!

**Comment by nikitin-da** [comment]
It seems it can be closed
