### ISSUE TITLE
Collection support for Query.whereArgs

### ISSUE THREAD

**Issue by fractalemagic** [pushtorefresh/storio#695]
Hey there,

Is there any reason why `Query.whereArgs` only accepts `List`s and not `Collection`s?

I tried to call whereArgs with a `Set` variable, which ended up calling whereArgs(Objects... args) because Set is a subclass of Collection rather than List.

This meant that it didn't handle my args properly ie. it treated my arg as an Object and called toString() on the Set itself, rather than on the elements in the Set.

It's not a big deal having to convert to a List, but to me, this was very unexpected behavior. This was because I was working with Kotlin's built in Collection extension methods, which unbeknownst to me, returned a Set rather than a List.

**Comment by artem-zinnatullin** [comment]
Hello, @fractalemagic!

The reason why we don't allow `Collection` is because `Collection` does not guarantee any ordering for the reader (most of implementations of `Set` don't), while arguments for `SQL` query must be ordered correctly in most types of the queries.

You can always convert your collection to `List` if you're sure about ordering, in Kotlin you can simply call `toList()`.

We're trying to be explicit with our API and prevent errors at compile time!

**Comment by fractalemagic** [comment]
Ah, that makes sense, thanks for the quick response!

**Comment by artem-zinnatullin** [comment]
np!
