### ISSUE TITLE
Standard Java support

### ISSUE THREAD

**Issue by fstephany** [pushtorefresh/storio#769]
I use storIO for an Android app that might need to be ported to the desktop. Both apps will continue to live.
I've started to decouple all my code from the Android framework. I'm wondering how much effort it would need to port StorIO to standard Java and cut the dependency on Android. I'm willing to do it but before diving into the code, I wanted to get your feedback.

**Comment by nikitin-da** [comment]
Hi, @fstephany 
If you have in mind some library for `SQLite` itself with the same api (`openhelper`, `cursor`, `contentValues` etc) like it do [Requery](https://github.com/requery/sqlite-android) but without android dependency:
than as far as I can see you should create your own [`DefaultStorIOSQLite`](https://github.com/pushtorefresh/storio/blob/master/storio-sqlite/src/main/java/com/pushtorefresh/storio/sqlite/impl/DefaultStorIOSQLite.java) implementation,
update imports and replace android specific annotations (NunNull, WorkerThread).
Otherwise I guess it will be hard to port it, because there are many usage of `Cursor`, `ConentValues` and so on

**Comment by fstephany** [comment]
Thanks, I'll have a look :)
It struck me yesterday but my tests are running with Robolectric and the SQLite queries works just fine on the JVM. I guess they have implemented the necessary plumbing to make it work.

I'll try and let you know.

**Comment by artem-zinnatullin** [comment]
Implementing classes with android package names should definitely work in my opinion and I would not say that it'll be *that* hard :)
