### ISSUE TITLE
Add `bulkInsert` support for ContentResolver

### ISSUE THREAD

**Issue by gautamjain** [pushtorefresh/storio#777]
Have you considered adding support for [`ContentResolver::bulkInsert`][1]?

---

If so, what's a good way I could go about starting that?  I could see the following changes:

- Add bulk insert support in `StorIOContentResolver.LowLevel`
  - `insert(InsertQuery query, ContentValues[] values)`
- Add a bulk insert flag in `PreparedPutCollectionOfObjects.Builder` and `PreparedPutContentValuesIterable.Builder`
  - `useBulkInsert(boolean bulkInsert)`
  - This would be similar to `useTransaction(...)`
- Modify or extend `PutResolver` or `DefaultPutResolver` with
  - `performPut(StorIOContentResolver storIOContentResolver, Iterable<ContentValues> contentValues)`

Have I overlooked something?

  [1]: https://developer.android.com/reference/android/content/ContentResolver.html#bulkInsert(android.net.Uri%2C%20android.content.ContentValues%5B%5D)

**Comment by artem-zinnatullin** [comment]
Yeah, the problem with `bulkInsert` is that it does not fit into StorIO model that well since default behavior is to make `query()` to find out whether we should `insert` or `update` the entry which is not possible with `bulkInsert`. Unfortunately, `bulkInsert` is not the same mechanism as `useTransaction`.

However, implementation under the hood of `bulkInsert` could use `SQLiteDatabase. insertWithOnConflict`, custom `insertOrUpdate` mechanism or even `StorIOSQLite.put()` (with transactions) so it is possible to make use of it with `StorIOContentResolver`.

Since we can't add some default behavior for it our current suggestion is to use `StorIOContentResolver.lowLevel().contentResolver()` and apply `bulkInsert` as you wish using custom type mapping where you can override how put operation should be performed.

cc @nikitin-da any input from you?

**Comment by nikitin-da** [comment]
Yep, `bulkInsert` doesn't match to "`put`-notation" and the simplest way to use it is call it directly on underlying content resolver, like @artem-zinnatullin suggest =(

**Comment by gautamjain** [comment]
Yeah, I did notice the default _put_ behavior was to `query` and then `insert` or `update` accordingly.

Instead of hacking this into _put_, could this be considered new database operation?  E.g. _import_ or maybe even _seed_?

If not, I'll go ahead and use `StorIOContentResolver.lowLevel().contentResolver()`.

Also, @artem-zinnatullin regarding your second paragraph - I don't own the `ContentProvider`.  I wanted to do a bulk insert into the Contacts Provider.

**Comment by artem-zinnatullin** [comment]
Well, we would like to keep Put, Get, Delete semantics if possible, very sad that `bulkInsert()` does not fit into it though…

Please go ahead and use `StorIOContentResolver.lowLevel().contentResolver()` for now.

I'm closing this issue, feel free to comment if you have some new input!
