### ISSUE TITLE
Receive Incremental updates when using Rx

### ISSUE THREAD

**Issue by nayeemzen** [pushtorefresh/storio#781]
From the [example](https://github.com/pushtorefresh/storio/blob/master/docs/StorIOContentResolver.md), we are receiving any updates to the database as the entire list of results. What is the recommended approach to receive incremental updates (e.g when a Tweet object is added, we only receive that one object instead of the entire list of tweets.)

```storIOContentResolver
  .get()
  .listOfObjects(Tweet.class)
  .withQuery(Query.builder()
    .uri(tweetsUri)
    .where("author = ?")
    .whereArgs("@artem_zin")
    .build())
  .prepare()
  .asRxObservable() // Get Result as rx.Observable and subscribe to further updates of Uri from Query!
  .observeOn(mainThread()) // All Rx operations work on Schedulers.io()
  .subscribe(tweets -> { // Please don't forget to unsubscribe
      // will be called with first result and then after each change of Uri from Query
      adapter.setData(tweets);
    }
  );
// don't forget to manage Subscription and unsubscribe in lifecycle methods to prevent memory leaks```

**Comment by nikitin-da** [comment]
Hi, @nayeemzen !
You can observe changes of uris and request entities manually:
```java
storIOContentResolver
        .observeChangesOfUris(TWEETS_URI)
        .map(affectedUri -> storIOContentResolver
                .get()
                .object(Tweet.class)
                .withQuery(createQueryForUri(affectedUri))
                .prepare()
                .executeAsBlocking()
        )
```

**Comment by geralt-encore** [comment]
I guess @nayeemzen was talking about fine-grained notifications if I understand it correctly.

**Comment by nayeemzen** [comment]
@nikitin-da thank you, yep I saw that in the API, I was eluding to more what @geralt-encore said. Btw awesome library, absolutely love it.

**Comment by nikitin-da** [comment]
Sorry, I forgot to note that you will receive uri for particular row only if [API >= 16](https://github.com/pushtorefresh/storio/blob/master/storio-content-resolver/src/main/java/com/pushtorefresh/storio/contentresolver/impl/RxChangesObserver.java#L48), but for [older versions](https://github.com/pushtorefresh/storio/blob/master/storio-content-resolver/src/main/java/com/pushtorefresh/storio/contentresolver/impl/RxChangesObserver.java#L78) it will be just common uri =( 

To have fine-grained notifications there is only way to filter updates before querying via rx filter:
```java
storIOContentResolver
        .observeChangesOfUris(TWEETS_URI)
        .filter(affectedUri -> checkIfUriSignificant(affectedUri))   //<< Filter changes before querying
        .map(affectedUri -> storIOContentResolver
                .get()
                .object(Tweet.class)
                .withQuery(createQueryForUri(affectedUri))
                .prepare()
                .executeAsBlocking()
        )
```
We can't add some tags or queries to [changes object](https://github.com/pushtorefresh/storio/blob/master/storio-content-resolver/src/main/java/com/pushtorefresh/storio/contentresolver/Changes.java#L14) to have unified way to identify the cause of change since in common case we aren't owners of the content provider =(

@nayeemzen thank you for your question and sorry for such delays=(
Fill free to comment and/or reopen=)

**Comment by artem-zinnatullin** [comment]
There are conceptual problems with incremental updates and SQL.

SQL allows you perform complex queries that can affect unknown (for StorIO)
entries in different tables of db, even simple things like "delete/update *
from table where something" will result in undefined behavior for naive
implementation of incremental updates, we were thinking about this feature
from the beginning of the project and haven't found a good solution yet :(
