### ISSUE TITLE
Bamboo Storage to StorIO

### ISSUE THREAD

**Issue by Merlinkoss** [pushtorefresh/storio#890]
I use Bamboo storage  in my project, 
But you impove this project to StorIO

How can i migrate?

**Comment by nikitin-da** [comment]
Hi, @Merlinkoss 
StorIO was completely rewritten since it was Bamboo storage =(
There are some analogies like:
`bambooStorage.addListener(ABambooStorageListener)` -> `storIOSQLite.observeChangesOfTag("particular_change_tag")` 
`bambooStorage.addOrUpdate(yourStorableItem)` -> `storIOSQLite.put()`
`bambooStorage.countOfItems(classOfStorableItems)` -> `storIOSQLite.get().umberOfResults()`
But it is totally different api, we didn't keep continuity of versioning from bamboo and all db calls must be rewritten from scratch
